version: '3.7'
services:
  front.test:
    build:
      dockerfile: './front.Dockerfile'
    stdin_open: true
    tty: true
    ports:
      - '11080:80'
      - '11022:22'
      - '3000:3000'
      - '24678:24678'
    volumes:
      - './front.test:/front.test'

  back.test:
    build:
      dockerfile: './back.Dockerfile'
    stdin_open: true
    tty: true
    ports:
      - '80:80'
      - '22:22'
    volumes:
      - './back.test:/back.test'

  back.db:
    image: mariadb/server:10.5
    ports:
      - '13306:3306'
      - '13022:22'
    environment:
      - 'MARIADB_ROOT_PASSWORD=docker123'
      - 'MARIADB_DATABASE=nuxt'
      - 'TZ=Asia/Seoul'
    command:
      - '--character-set-server=utf8'
      - '--collation-server=utf8_general_ci'
    volumes:
      - './docker-mysql/mysql:/var/lib/mysql'